#!/usr/bin/env python3

from verif import basic_verif
from verif import verif_args_values
from get_args import get_arguments
from first_connection import connect_socket
from first_connection import get_client_nb_and_world_size
import socket
import sys

def main():
    """Main wesh"""
    basic_verif()
    opt = get_arguments()
    verif_args_values(opt)

    print(opt, "\n")

    server_socket = connect_socket(opt)
    client_info = get_client_nb_and_world_size(server_socket, opt)
    print("Client info -> ", client_info)


if __name__ == '__main__':
    try :
        main()
    except :
        sys.exit(84)